name: Upload to Space

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run UI jvmJar
        run: ./gradlew :secondary:ui:jvmJar
      - name: Build Sensitively
        run: ./gradlew sensitive-build

  primary:
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Upload Primary Libs to Space
        env:
          SPACE_USERNAME: ${{ secrets.SPACE_USERNAME }}
          SPACE_PASSWORD: ${{ secrets.SPACE_PASSWORD }}
        run: ./gradlew upload-primary

  secondary:
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Upload Secondary Libs to Space
        env:
          SPACE_USERNAME: ${{ secrets.SPACE_USERNAME }}
          SPACE_PASSWORD: ${{ secrets.SPACE_PASSWORD }}
        run: ./gradlew upload-secondary
  tertiary:
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Upload Tertiary Libs to Space
        env:
          SPACE_USERNAME: ${{ secrets.SPACE_USERNAME }}
          SPACE_PASSWORD: ${{ secrets.SPACE_PASSWORD }}
        run: ./gradlew upload-tertiary
  ui-libs:
    needs: builld
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Upload UI Libs to Space
        env:
          SPACE_USERNAME: ${{ secrets.SPACE_USERNAME }}
          SPACE_PASSWORD: ${{ secrets.SPACE_PASSWORD }}
        run: ./gradlew upload-ui-libs